import express from "express";
import { authorizeJwt } from "@middlewares/auth.middleware";
import { addHoliday, deleteHolidayById, getAllHoliday, getHolidayById, updateHolidayById } from "../controllers/holiday.controller";
const router = express.Router();
router.post("/", authorizeJwt, addHoliday);
router.get("/", authorizeJwt, getAllHoliday);
router.get("/getById/:id", authorizeJwt, getHolidayById);
router.patch("/updateById/:id", authorizeJwt, updateHolidayById);
router.delete("/deleteById/:id", authorizeJwt, deleteHolidayById);
export default router;
