import express from 'express';
import { authorizeJwt } from '../../middlewares/auth.middleware';
import { addBom, deleteBomById, getAllBom, getBomById, updateBomById } from '../controllers/bom.controller';
const router = express.Router();
router.post('/', authorizeJwt, addBom);
router.get('/', authorizeJwt, getAllBom);
router.get('/getById/:id', authorizeJwt, getBomById);
router.patch('/updateById/:id', authorizeJwt, updateBomById);
router.delete('/deleteById/:id', authorizeJwt, deleteBomById);
export default router;