export const REQUEST_TYPES = {
    SALES_ORDER: {
        ADD: "SALES_ORDER_ADD",
        DELETE: "SALES_ORDER_DELETE",
        UPDATE: "SALES_ORDER_UPDATE",
    },
    RAW_MATERIAL_PURCHASE_INDENT: {
        ADD: "RAW_MATERIAL_PURCHASE_INDENT_ADD",
        DELETE: "RAW_MATERIAL_PURCHASE_INDENT_DELETE",
        UPDATE: "RAW_MATERIAL_PURCHASE_INDENT_UPDATE",
    },
    RAW_MATERIAL_PURCHASE_ORDER: {
        ADD: "RAW_MATERIAL_PURCHASE_ORDER_ADD",
        DELETE: "RAW_MATERIAL_PURCHASE_ORDER_DELETE",
        UPDATE: "RAW_MATERIAL_PURCHASE_ORDER_UPDATE",
    },
} as const;

export type REQUEST_TYPES_TYPE = keyof typeof REQUEST_TYPES;

export type REQUEST_TYPES_STRINGS = (typeof REQUEST_TYPES)[keyof typeof REQUEST_TYPES][keyof (typeof REQUEST_TYPES)[REQUEST_TYPES_TYPE]]; // TO GET ALL REQUEST_TYPES STRINGS []
